name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release Version"
        required: true
        type: string

jobs:
  read-inputs:
    runs-on: ubuntu-latest
    outputs:
      iteration: ${{ steps.extract.outputs.ITERATION }}
      imagetag: ${{ steps.extract.outputs.IMAGETAG }}
      db: ${{ steps.extract.outputs.DB }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Inputs from File
        id: extract
        run: |
          RELEASE_VERSION=${{ inputs.release }}
          FILE_PATH="release/${RELEASE_VERSION}/input.txt"

          if [ ! -f "$FILE_PATH" ]; then
            echo "File not found: $FILE_PATH"
            exit 1
          fi

          ITERATION=$(awk '/\[ITERATION\]/{getline; print}' $FILE_PATH | tr -d '[:space:]')
          IMAGETAG=$(awk '/\[IMAGETAG\]/{getline; print; getline; print}' $FILE_PATH | tr '\n' ',' | sed 's/,$//')
          DB=$(awk '/\[DB\]/{getline; print}' $FILE_PATH | tr -d '[:space:]')

          echo "ITERATION=$ITERATION"
          echo "IMAGETAG=$IMAGETAG"
          echo "DB=$DB"

          echo "ITERATION=$ITERATION" >> $GITHUB_OUTPUT
          echo "IMAGETAG=$IMAGETAG" >> $GITHUB_OUTPUT
          echo "DB=$DB" >> $GITHUB_OUTPUT

  deploy:
    needs: read-inputs
    runs-on: ubuntu-latest
    steps:
      - name: Use Extracted Environment Variables
        run: |
          echo "Deploying with Iteration: ${{ needs.read-inputs.outputs.iteration }}"
          echo "Using ImageTag: ${{ needs.read-inputs.outputs.imagetag }}"
          echo "Connecting to DB: ${{ needs.read-inputs.outputs.db }}"
