name: Validate User Input

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the main branch

jobs:
  validate-input:
    runs-on: ubuntu-latest  # Runs on the latest Ubuntu virtual environment

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # Checkout the repository so the Action can access files

      - name: Set input value
        id: input  # Define an input variable (could be set dynamically or manually)
        run: |
          echo "user_input=input1" >> $GITHUB_ENV  # Hardcoded input for demonstration (can be dynamic)

      - name: Validate the user input
        run: |
          # Read the valid inputs from the valid_inputs.txt file
          valid_inputs=$(cat Input.txt)
          
          # Get the user input from the environment variable
          user_input=$USER_INPUT
          
          # Check if the user input is in the valid inputs list
          if echo "$valid_inputs" | grep -qx "$user_input"; then
            echo "Valid input!"
          else
            echo "Invalid input!"
            exit 1  # Fail the action if the input is invalid
          fi

      - name: Output validation result
        run: |
          if [ $? -eq 0 ]; then
            echo "Input is valid!"
          else
            echo "Input is invalid!"
          fi

