name: Validate File Existence

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the file name to validate'
        required: true
        default: 'README.md'  # Default value, can be changed when triggering manually

jobs:
  validate-file:
    runs-on: ubuntu-latest  # Specify the virtual environment (Ubuntu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository so we can access the files

      - name: Validate if file exists
        run: |
          # Get the filename from the input parameter
          file_name="${{ github.event.inputs.filename }}"

          # Check if the file exists in the repository
          if [ -f "$file_name" ]; then
            echo "The file '$file_name' exists in the repository."
          else
            echo "The file '$file_name' does not exist in the repository."
            exit 1  # Fail the workflow if the file doesn't exist
          fi
