name: Validate File Existence

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the file name to validate'
        required: true
        
jobs:
  validate-file:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository so we can access the files

      - name: Set folder path
        run: |
          
          folder_path="realse"  # Set the folder path (change this to your folder)
        
          file_name="${{ github.event.inputs.filename }}"

          
          full_path="$folder_path/$file_name"
          
          
          if [ -f "$full_path" ]; then
            echo "The file '$file_name' exists in the '$folder_path' folder."
          else
            echo "The file '$file_name' does not exist in the '$folder_path' folder."
            exit 1  
          fi
