name: File Validation Workflow

on:
  workflow_dispatch:
    inputs:
      file-name:
        description: 'Enter the name of the file to validate '
        required: true
        
      search-key:
        description: 'Enter the key '
        required: true
        

jobs:
  validate-file:
    runs-on: ubuntu-latest  

    steps:
      
      - name: Checkout repository code
        uses: actions/checkout@v2

      
      - name: Get file name and search key input
        id: inputs
        run: |
          echo "File name input: ${{ github.event.inputs['file-name'] }}"
          echo "Search key input: ${{ github.event.inputs['search-key'] }}"

      
      - name: Search for the file in the repository
        id: search_file
        run: |
          file_name="${{ github.event.inputs['file-name'] }}"
          # Search for the file in the entire repository
          file_path=$(find . -type f -name "$file_name")
          
          if [ -z "$file_path" ]; then
            echo "File not found: $file_name"
            exit 1  # Exit the job if the file is not found
          else
            echo "File found at: $file_path"
            echo "::set-output name=file_path::$file_path" 
          fi

     
      - name: Validate file name
        id: validate_file_name
        run: |
          file_name="${{ github.event.inputs['file-name'] }}"
          extension="${file_name##*.}"
          
        
          if [ "$extension" == "txt" ]; then
            echo "File name is valid (it has a .txt extension)."
          else
            echo "Invalid file extension. Only .txt files are allowed."
            exit 1  
          fi

     
      - name: Print specific content from the file
        run: |
          
          file_path="${{ steps.search_file.outputs.file_path }}"
          search_key="${{ github.event.inputs['search-key'] }}" 
          echo "Searching for '$search_key' in $file_path"
          
          value=""      
          while IFS= read -r line; do
            if [[ "$line" == "$search_key:"* ]]; then
              value="${line#*: }"
              break  
            fi
          done < "$file_path"

          
          if [ -n "$value" ]; then
            echo "Value for '$search_key': $value"
          else
            echo "Key '$search_key' not found in the file."
          fi
