name: Validate File Existence

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Enter the file name to validate'
        required: true
        
jobs:
  validate-file:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Clone the repository so we can access the files

      - name: Set folder path
        run: |
          # Define the folder where we want to check the file
          folder_path="realse"  # Set the folder path (change this to your folder)
          
          # Get the filename input from the workflow_dispatch
          file_name="${{ github.event.inputs.filename }}"

          # Construct the full path to the file
          full_path="$folder_path/$file_name"
          
          # Check if the file exists in the specified folder
          if [ -f "$full_path" ]; then
            echo "The file '$file_name' exists in the '$folder_path' folder."
          else
            echo "The file '$file_name' does not exist in the '$folder_path' folder."
            exit 1  # Fail the workflow if the file doesn't exist
          fi
