name: File Validation Workflow

on:
  workflow_dispatch:
    inputs:
      iteration:
        description: 'Enter the directory name and ITERATION value'
        required: true

jobs:
  validate-file:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Iteration input
        id: inputs
        run: |
          echo "Iteration input: ${{ github.event.inputs['iteration'] }}"

      - name: Search directories in the release directory and validate
        id: search_file
        run: |
          release_dir="release"
          input_iteration="${{ github.event.inputs['iteration'] }}"  
          
          for dir in "$release_dir"/*; do
            if [ -d "$dir" ]; then
              iteration=$(basename "$dir")  # Get the directory name, e.g., '2305'

              if [ "$iteration" != "$input_iteration" ]; then
                continue
              fi
              
              text_file=$(find "$dir" -type f -name "*.txt")

              if [ -z "$text_file" ]; then
                echo "No .txt file found in directory $dir"
                continue
              fi

              echo "Checking directory: $dir"
              echo "Looking for ITERATION: $iteration in the file"

              iteration_found=""
              while IFS= read -r line; do
                if [[ "$line" =~ ^ITERATION:\ *([0-9]+) ]]; then
                  file_iteration="${BASH_REMATCH[1]}"  
                  iteration_found="$file_iteration"
                  break
                fi
              done < "$text_file"

              
              if [ "$iteration_found" == "$iteration" ]; then
                echo "ITERATION matches the directory name ($iteration). Setting environment variables."

                export ITERATION=$(grep 'ITERATION' "$text_file" | cut -d':' -f2 | xargs)
                export IMAGETAG=$(grep 'IMAGETAG' "$text_file" | cut -d':' -f2 | xargs)
                export DB=$(grep 'DB' "$text_file" | cut -d':' -f2 | xargs)

                
                echo "ITERATION=$ITERATION" >> $GITHUB_ENV
                echo "IMAGETAG=$IMAGETAG" >> $GITHUB_ENV
                echo "DB=$DB" >> $GITHUB_ENV

              else
                echo "ITERATION in the file does not match the directory name ($iteration). Skipping this file."
                exit 1
              fi
            fi
          done

      - name: Use the environment variables and print
        run: |
          echo "Iteration: $ITERATION"
          echo "Image Tag: $IMAGETAG"
          echo "Database: $DB"
